/**
 * Downloads the woff2 subsets we actually need (latin + latin-ext, for the
 * Catalan ela geminada ŀ/Ŀ and the full accent set) and writes a self-hosted
 * public/fonts/fonts.css. No external font CDN at runtime.
 *
 * Run manually: pnpm node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public', 'fonts');

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const FAMILIES = [
  'Bricolage+Grotesque:opsz,wdth,wght@12..96,75..100,300..800',
  'Newsreader:ital,opsz,wght@0,6..72,300..700;1,6..72,300..700',
  'IBM+Plex+Mono:wght@400;500',
];

const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const css = await fetch(
  `https://fonts.googleapis.com/css2?family=${FAMILIES.join('&family=')}&display=swap`,
  { headers: { 'User-Agent': UA } },
).then((r) => r.text());

await mkdir(OUT, { recursive: true });

const blocks = [];
let subset = null;
let current = null;
let counter = 0;

for (const line of css.split('\n')) {
  const comment = line.match(/^\/\*\s*(\S+)\s*\*\/$/);
  if (comment) {
    subset = comment[1];
    continue;
  }
  if (line.trim() === '@font-face {') {
    current = { subset, props: [], url: null };
    continue;
  }
  if (!current) continue;
  if (line.trim() === '}') {
    if (WANTED_SUBSETS.has(current.subset)) blocks.push(current);
    current = null;
    continue;
  }
  const src = line.match(/src:\s*url\((\S+)\)/);
  if (src) {
    current.url = src[1];
    continue;
  }
  const prop = line.trim().replace(/;$/, '');
  if (prop && !prop.startsWith('font-display')) current.props.push(prop);
}

const out = [
  '/* Self-hosted subsets — latin + latin-ext (Catalan ŀ/Ŀ, ç, accents).',
  '   Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */',
  '',
];

for (const block of blocks) {
  const family = block.props.find((p) => p.startsWith('font-family'))?.split(': ')[1] ?? 'font';
  const style = block.props.find((p) => p.startsWith('font-style'))?.includes('italic')
    ? 'italic'
    : 'normal';
  const name = `${slug(family.replace(/'/g, ''))}-${block.subset}-${style}-${counter++}.woff2`;
  const bytes = Buffer.from(await fetch(block.url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
  await writeFile(path.join(OUT, name), bytes);
  out.push('@font-face {');
  for (const p of block.props) out.push(`  ${p};`);
  out.push('  font-display: swap;');
  out.push(`  src: url('/fonts/${name}') format('woff2');`);
  out.push('}');
  out.push('');
  console.log(`${name}  ${(bytes.length / 1024).toFixed(1)} kB  (${block.subset})`);
}

await writeFile(path.join(OUT, 'fonts.css'), out.join('\n'));
console.log(`\n${blocks.length} faces → public/fonts/fonts.css`);
